<a href="https://colab.research.google.com/github/alro923/Deep_learning_with_python/blob/master/numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[numpy devdocs link](https://numpy.org/devdocs/index.html)

In [0]:
import numpy as np

In [8]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Numpy
* NumPy는 행렬이나 일반적으로 대규모 다차원 배열을 쉽게 처리 할 수 있도록 지원하는 파이썬의 라이브러리이다.
* NumPy는 데이터 구조 외에도 수치 계산을 위해 효율적으로 구현된 기능을 제공한다.

# Arange : 숫자들을 array 형태로 반환
* numpy.arange([start, ]stop, [step, ]dtype=None)
* 반열린구간 [start, stop) 에서 step 의 크기만큼 일정하게 떨어져 있는 숫자들을 array 형태로 반환해 주는 함수다.

In [9]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Random : 난수생성

In [3]:
np.random.seed(0) # 시드 설정, 0과 같거나 큰 정수를 넣어준다.
np.random.rand(5) # 5개의 난수 생성

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [4]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [5]:
np.random.seed(0)
np.random.rand(5) # 시드가 같으면, 동일한 갯수일때 동일한 난수 발생

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [13]:
# numpy.random.randint(low, high=None, size=None)
# 만약 high를 입력하지 않으면 0과 low사이의 숫자를, high를 입력하면 low와 high는 사이의 숫자를 출력한다. size는 난수의 숫자이다.
# 과대적합을 방지하기 위해 드롭아웃 층을 추가할때 사용함

np.random.randint(0, high = 2, size = 5)

array([1, 0, 0, 1, 0])

In [16]:
np.random.randint(0, high = 100, size = 10)

array([88, 88, 12, 58, 65, 39, 87, 46, 88, 81])